// Code generated by scripts/gen-ops-schema.mjs from contracts/ops/project.schema.json. DO NOT EDIT.

export const schemaVersion = 1

export type Point = { x: number; y: number }

export type AssumptionSetsRecord = {
  id: string
  order: string
  availability: number | null
  comm_rub_per_robot_year: number | null
  delivery_share: number | null
  discount_rate: number | null
  labor_cash_share: number
  name: string
  prices_include_vat: boolean
  reserve: number | null
  service_share: number | null
  technician_wage_month_rub: number | null
  utilization: number | null
  vat_rate: number
  vat_recoverable: boolean
}

export type AssumptionSetsInsert = {
  order: string
  availability?: number | null
  comm_rub_per_robot_year?: number | null
  delivery_share?: number | null
  discount_rate?: number | null
  labor_cash_share: number
  name: string
  prices_include_vat?: boolean
  reserve?: number | null
  service_share?: number | null
  technician_wage_month_rub?: number | null
  utilization?: number | null
  vat_rate: number
  vat_recoverable?: boolean
}

export type FinancingRecord = {
  id: string
  assumptions: unknown
  kind: 'buy' | 'raas'
  tariff: 'fixed' | 'variable' | 'mixed' | null
  variant_id: string
}

export type FinancingInsert = {
  assumptions: unknown
  kind: 'buy' | 'raas'
  tariff?: 'fixed' | 'variable' | 'mixed' | null
  variant_id: string
}

export type FleetItemsRecord = {
  id: string
  order: string
  price_override_reason: string
  price_override_rub: number | null
  quantity: number
  solution_id: string | null
  task_codes: string[]
  variant_id: string
}

export type FleetItemsInsert = {
  order: string
  price_override_reason?: string
  price_override_rub?: number | null
  quantity: number
  solution_id?: string | null
  task_codes?: string[]
  variant_id: string
}

export type MapRecord = {
  id: string
  check: unknown
  meters_per_px: number
  page: unknown
  profile: 'indoor' | 'airspace' | 'field'
  segment: unknown
}

export type MapEdgesRecord = {
  id: string
  bidirectional: boolean | null
  from: string
  to: string
  width_m: number | null
}

export type MapEdgesInsert = {
  bidirectional?: boolean | null
  from: string
  to: string
  width_m?: number | null
}

export type MapFlowsRecord = {
  id: string
  drop_point_ids: string[]
  pickup_point_ids: string[]
  process_code: string
}

export type MapFlowsInsert = {
  drop_point_ids?: string[]
  pickup_point_ids?: string[]
  process_code: string
}

export type MapObstaclesRecord = {
  id: string
  order: string
  kind: 'rack' | 'wall' | 'column' | 'other'
  name: string
  ring: Point[]
}

export type MapObstaclesInsert = {
  order: string
  kind: 'rack' | 'wall' | 'column' | 'other'
  name?: string
  ring: Point[]
}

export type MapPointsRecord = {
  id: string
  kind: 'task' | 'dock' | 'charger' | 'gate' | 'other'
  name: string
  pos: Point
  process_code: string | null
}

export type MapPointsInsert = {
  kind: 'task' | 'dock' | 'charger' | 'gate' | 'other'
  name?: string
  pos: Point
  process_code?: string | null
}

export type MapResourcesRecord = {
  id: string
  capacity: number
  edge_ids: string[]
  kind: 'dock' | 'narrow_aisle' | 'charger'
  name: string
  point_id: string | null
  point_ids: string[]
}

export type MapResourcesInsert = {
  capacity: number
  edge_ids?: string[]
  kind: 'dock' | 'narrow_aisle' | 'charger'
  name?: string
  point_id?: string | null
  point_ids?: string[]
}

export type MapZonesRecord = {
  id: string
  order: string
  kind: 'workspace' | 'storage' | 'dock_area' | 'pick' | 'charge' | 'other'
  name: string
  ring: Point[]
}

export type MapZonesInsert = {
  order: string
  kind: 'workspace' | 'storage' | 'dock_area' | 'pick' | 'charge' | 'other'
  name?: string
  ring: Point[]
}

export type ProcessesRecord = {
  id: string
  order: string
  baseline_staff: unknown
  code: string
  demand: unknown
  durations: unknown
  is_baseline: boolean
  name: string
  point_ids: string[]
  sla: unknown
  task_type: 'pallet_inbound' | 'pallet_putaway' | 'pallet_outbound' | 'piece_pick' | 'pallet_move' | 'cleaning'
}

export type ProcessesInsert = {
  order: string
  baseline_staff: unknown
  code: string
  demand: unknown
  durations: unknown
  is_baseline?: boolean
  name: string
  point_ids?: string[]
  sla: unknown
  task_type: 'pallet_inbound' | 'pallet_putaway' | 'pallet_outbound' | 'piece_pick' | 'pallet_move' | 'cleaning'
}

export type ProjectRecord = {
  id: string
  active_assumption_set_id: string | null
  econ_overrides: unknown
  match_selected_ids: unknown
  name: string
  object_type: 'warehouse' | 'airport' | 'hospital'
  params: Record<string, unknown>
  reviewed_tabs: unknown
}

export type SharedCostsRecord = {
  id: string
  order: string
  bucket: 'capex' | 'opex'
  code: string
  label: string
  rub: number
}

export type SharedCostsInsert = {
  order: string
  bucket: 'capex' | 'opex'
  code: string
  label: string
  rub: number
}

export type VariantsRecord = {
  id: string
  order: string
  name: string
  notes: string
  status: 'draft' | 'ready'
}

export type VariantsInsert = {
  order: string
  name: string
  notes?: string
  status: 'draft' | 'ready'
}

export type Records = {
  assumption_sets: AssumptionSetsRecord
  financing: FinancingRecord
  fleet_items: FleetItemsRecord
  map: MapRecord
  map_edges: MapEdgesRecord
  map_flows: MapFlowsRecord
  map_obstacles: MapObstaclesRecord
  map_points: MapPointsRecord
  map_resources: MapResourcesRecord
  map_zones: MapZonesRecord
  processes: ProcessesRecord
  project: ProjectRecord
  shared_costs: SharedCostsRecord
  variants: VariantsRecord
}

export type Inserts = {
  assumption_sets: AssumptionSetsInsert
  financing: FinancingInsert
  fleet_items: FleetItemsInsert
  map_edges: MapEdgesInsert
  map_flows: MapFlowsInsert
  map_obstacles: MapObstaclesInsert
  map_points: MapPointsInsert
  map_resources: MapResourcesInsert
  map_zones: MapZonesInsert
  processes: ProcessesInsert
  shared_costs: SharedCostsInsert
  variants: VariantsInsert
}

export type CollectionName = keyof Records
export type SingletonName = 'map' | 'project'
export type ListName = keyof Inserts
export type OrderedName = 'assumption_sets' | 'fleet_items' | 'map_obstacles' | 'map_zones' | 'processes' | 'shared_costs' | 'variants'

export type KeyedField = {
  assumption_sets: never
  financing: 'assumptions'
  fleet_items: never
  map: 'check' | 'page' | 'segment'
  map_edges: never
  map_flows: never
  map_obstacles: never
  map_points: never
  map_resources: never
  map_zones: never
  processes: 'baseline_staff' | 'demand' | 'durations' | 'sla'
  project: 'econ_overrides' | 'match_selected_ids' | 'params' | 'reviewed_tabs'
  shared_costs: never
  variants: never
}

export type SetPath<C extends CollectionName> = Exclude<keyof Records[C], 'id' | 'order'> | `${KeyedField[C]}.${string}`

export type Op =
  | { [C in ListName]: { op: 'insert'; coll: C; id: string; value: Inserts[C] } }[ListName]
  | { [C in CollectionName]: { op: 'set'; coll: C; id?: string; path: SetPath<C>; value: unknown } }[CollectionName]
  | { op: 'delete'; coll: ListName; id: string }
  | { op: 'move'; coll: OrderedName; id: string; order: string }
