// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssumptionSet struct {
	ID                     uuid.UUID      `json:"id"`
	ProjectID              uuid.UUID      `json:"project_id"`
	Name                   string         `json:"name"`
	IsActive               bool           `json:"is_active"`
	VatRate                pgtype.Numeric `json:"vat_rate"`
	PricesIncludeVat       bool           `json:"prices_include_vat"`
	VatRecoverable         bool           `json:"vat_recoverable"`
	LaborCashShare         pgtype.Numeric `json:"labor_cash_share"`
	SortOrder              int32          `json:"sort_order"`
	OrderKey               string         `json:"order_key"`
	DiscountRate           pgtype.Numeric `json:"discount_rate"`
	Utilization            pgtype.Numeric `json:"utilization"`
	Availability           pgtype.Numeric `json:"availability"`
	Reserve                pgtype.Numeric `json:"reserve"`
	ServiceShare           pgtype.Numeric `json:"service_share"`
	DeliveryShare          pgtype.Numeric `json:"delivery_share"`
	CommRubPerRobotYear    pgtype.Numeric `json:"comm_rub_per_robot_year"`
	TechnicianWageMonthRub pgtype.Numeric `json:"technician_wage_month_rub"`
}

type AuditEvent struct {
	ID          int64              `json:"id"`
	At          pgtype.Timestamptz `json:"at"`
	ActorUserID *uuid.UUID         `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    *string            `json:"target_id"`
	RequestID   *string            `json:"request_id"`
	Meta        json.RawMessage    `json:"meta"`
}

type CalculationResult struct {
	RunID     uuid.UUID          `json:"run_id"`
	Summary   json.RawMessage    `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CalculationRun struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	ProjectVersionID uuid.UUID          `json:"project_version_id"`
	InputHash        string             `json:"input_hash"`
	MatchVersion     string             `json:"match_version"`
	EconVersion      string             `json:"econ_version"`
	SimVersion       string             `json:"sim_version"`
	Seed             int32              `json:"seed"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Kind             string             `json:"kind"`
	ConfidenceLevel  string             `json:"confidence_level"`
	DraftSeq         *int64             `json:"draft_seq"`
	DraftHash        *string            `json:"draft_hash"`
}

type CatalogExport struct {
	ID        uuid.UUID          `json:"id"`
	CreatedBy *uuid.UUID         `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Snapshot  json.RawMessage    `json:"snapshot"`
}

type CatalogImport struct {
	ID        uuid.UUID          `json:"id"`
	CreatedBy *uuid.UUID         `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	FileName  string             `json:"file_name"`
	Mode      string             `json:"mode"`
	ExportID  *uuid.UUID         `json:"export_id"`
	Grid      json.RawMessage    `json:"grid"`
	Mapping   json.RawMessage    `json:"mapping"`
	Status    string             `json:"status"`
	Summary   json.RawMessage    `json:"summary"`
}

type EmailOutbox struct {
	ID            uuid.UUID          `json:"id"`
	ToEmail       string             `json:"to_email"`
	Template      string             `json:"template"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	ErrorText     *string            `json:"error_text"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
}

type EmailToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type FinancingScenario struct {
	ID          uuid.UUID       `json:"id"`
	VariantID   uuid.UUID       `json:"variant_id"`
	Kind        string          `json:"kind"`
	Tariff      *string         `json:"tariff"`
	Assumptions json.RawMessage `json:"assumptions"`
}

type Invitation struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	TokenHash      []byte             `json:"token_hash"`
	InvitedBy      *uuid.UUID         `json:"invited_by"`
	ProjectID      *uuid.UUID         `json:"project_id"`
	ProjectRole    *string            `json:"project_role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	AcceptedUserID *uuid.UUID         `json:"accepted_user_id"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Project struct {
	ID           uuid.UUID          `json:"id"`
	UserID       *uuid.UUID         `json:"user_id"`
	Name         string             `json:"name"`
	ObjectType   string             `json:"object_type"`
	Params       json.RawMessage    `json:"params"`
	ModelVersion string             `json:"model_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Results      []byte             `json:"results"`
	CalcSeed     *int32             `json:"calc_seed"`
	Status       string             `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CurrentRunID *uuid.UUID         `json:"current_run_id"`
	InputHash    string             `json:"input_hash"`
	DraftSeq     int64              `json:"draft_seq"`
	DeletedBy    *uuid.UUID         `json:"deleted_by"`
}

type ProjectDraft struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Document  json.RawMessage    `json:"document"`
	InputHash string             `json:"input_hash"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	AddedBy   *uuid.UUID         `json:"added_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectOperation struct {
	ID              int64              `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Seq             *int64             `json:"seq"`
	TxID            uuid.UUID          `json:"tx_id"`
	ClientID        string             `json:"client_id"`
	ActorUserID     *uuid.UUID         `json:"actor_user_id"`
	Label           string             `json:"label"`
	Ops             json.RawMessage    `json:"ops"`
	RejectedReason  *string            `json:"rejected_reason"`
	RejectedDetails []byte             `json:"rejected_details"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProjectProcess struct {
	ID            uuid.UUID       `json:"id"`
	ProjectID     uuid.UUID       `json:"project_id"`
	Code          string          `json:"code"`
	Name          string          `json:"name"`
	TaskType      string          `json:"task_type"`
	IsBaseline    bool            `json:"is_baseline"`
	Demand        json.RawMessage `json:"demand"`
	Sla           json.RawMessage `json:"sla"`
	PointIds      json.RawMessage `json:"point_ids"`
	Durations     json.RawMessage `json:"durations"`
	BaselineStaff json.RawMessage `json:"baseline_staff"`
	SortOrder     int32           `json:"sort_order"`
	OrderKey      string          `json:"order_key"`
}

type ProjectVersion struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	VersionNo int32              `json:"version_no"`
	Snapshot  json.RawMessage    `json:"snapshot"`
	InputHash string             `json:"input_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scenario struct {
	ID         uuid.UUID       `json:"id"`
	ProjectID  uuid.UUID       `json:"project_id"`
	Kind       string          `json:"kind"`
	SolutionID *uuid.UUID      `json:"solution_id"`
	Inputs     json.RawMessage `json:"inputs"`
	Results    json.RawMessage `json:"results"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CsrfToken  string             `json:"csrf_token"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	UserAgent  string             `json:"user_agent"`
	IpPrefix   string             `json:"ip_prefix"`
}

type SharedCostItem struct {
	ID        uuid.UUID      `json:"id"`
	ProjectID uuid.UUID      `json:"project_id"`
	Code      string         `json:"code"`
	Label     string         `json:"label"`
	Bucket    string         `json:"bucket"`
	Rub       pgtype.Numeric `json:"rub"`
	SortOrder int32          `json:"sort_order"`
	OrderKey  string         `json:"order_key"`
}

type SimulationArtifact struct {
	ID         uuid.UUID          `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	Kind       string             `json:"kind"`
	Encoding   string             `json:"encoding"`
	Data       []byte             `json:"data"`
	SizeBytes  int32              `json:"size_bytes"`
	RawBytes   int32              `json:"raw_bytes"`
	EventCount int32              `json:"event_count"`
	Pinned     bool               `json:"pinned"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SimulationJob struct {
	ID                uuid.UUID          `json:"id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	RunID             *uuid.UUID         `json:"run_id"`
	Status            string             `json:"status"`
	ProgressPct       int32              `json:"progress_pct"`
	Attempt           int32              `json:"attempt"`
	ErrorText         *string            `json:"error_text"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CanceledAt        pgtype.Timestamptz `json:"canceled_at"`
	UserID            *uuid.UUID         `json:"user_id"`
	Config            json.RawMessage    `json:"config"`
	MaxAttempts       int32              `json:"max_attempts"`
	ReplicationsTotal int32              `json:"replications_total"`
	ReplicationsDone  int32              `json:"replications_done"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	HeartbeatAt       pgtype.Timestamptz `json:"heartbeat_at"`
}

type SimulationReplication struct {
	RunID     uuid.UUID          `json:"run_id"`
	Idx       int32              `json:"idx"`
	Seed      int64              `json:"seed"`
	Status    string             `json:"status"`
	Metrics   json.RawMessage    `json:"metrics"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Solution struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Vendor       *string            `json:"vendor"`
	Kind         *string            `json:"kind"`
	Subtype      *string            `json:"subtype"`
	Status       *string            `json:"status"`
	Industry     *string            `json:"industry"`
	Scenario     *string            `json:"scenario"`
	PriceRub     pgtype.Numeric     `json:"price_rub"`
	SourceUrl    *string            `json:"source_url"`
	Raw          json.RawMessage    `json:"raw"`
	Family       *string            `json:"family"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
	EditedAt     pgtype.Timestamptz `json:"edited_at"`
	FieldSources json.RawMessage    `json:"field_sources"`
}

type SolutionImage struct {
	SolutionID  uuid.UUID          `json:"solution_id"`
	ContentType string             `json:"content_type"`
	Bytes       []byte             `json:"bytes"`
	Sha256      string             `json:"sha256"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SolutionSpec struct {
	SolutionID     uuid.UUID          `json:"solution_id"`
	PayloadKg      pgtype.Numeric     `json:"payload_kg"`
	MassKg         pgtype.Numeric     `json:"mass_kg"`
	LengthMm       pgtype.Numeric     `json:"length_mm"`
	WidthMm        pgtype.Numeric     `json:"width_mm"`
	HeightMm       pgtype.Numeric     `json:"height_mm"`
	SpeedMps       pgtype.Numeric     `json:"speed_mps"`
	EnduranceH     pgtype.Numeric     `json:"endurance_h"`
	ChargeMin      pgtype.Numeric     `json:"charge_min"`
	NavType        *string            `json:"nav_type"`
	PosAccuracyMm  pgtype.Numeric     `json:"pos_accuracy_mm"`
	MinAisleMm     pgtype.Numeric     `json:"min_aisle_mm"`
	TempMinC       pgtype.Numeric     `json:"temp_min_c"`
	TempMaxC       pgtype.Numeric     `json:"temp_max_c"`
	LifetimeYears  pgtype.Numeric     `json:"lifetime_years"`
	ServicePctYear pgtype.Numeric     `json:"service_pct_year"`
	Confidence     *string            `json:"confidence"`
	SourcedAt      pgtype.Timestamptz `json:"sourced_at"`
	TurnRadiusMm   pgtype.Numeric     `json:"turn_radius_mm"`
}

type SolutionVariant struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Notes     string             `json:"notes"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrderKey  string             `json:"order_key"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	Role              string             `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	DisabledAt        pgtype.Timestamptz `json:"disabled_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
}

type VariantFleetItem struct {
	ID                  uuid.UUID       `json:"id"`
	VariantID           uuid.UUID       `json:"variant_id"`
	SolutionID          *uuid.UUID      `json:"solution_id"`
	Quantity            int32           `json:"quantity"`
	TaskCodes           json.RawMessage `json:"task_codes"`
	PriceOverrideRub    pgtype.Numeric  `json:"price_override_rub"`
	PriceOverrideReason string          `json:"price_override_reason"`
	SortOrder           int32           `json:"sort_order"`
	OrderKey            string          `json:"order_key"`
}
