[book]
title = "Платформа подбора роботизированных решений"
language = "ru"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true
site-url = "/hldt26_rp/"
git-repository-url = "https://github.com/ogswag/hldt26_rp"
